2024-07-02 13:43:28.741 +05:30 [ERR] {"message":"An error occurred while saving the entity changes. See the inner exception for details.\nThe INSERT statement conflicted with the FOREIGN KEY constraint \"FK__Tasks__StatusId__6477ECF3\". The conflict occurred in database \"Nikhil_ToDoApp\", table \"dbo.Statuses\", column 'StatusId'.\n","user":"1","endPoint":"ToDoAppWebApi.Controllers.TasksController.AddTask (ToDoAppWebApi)"}
2024-07-02 13:53:36.504 +05:30 [ERR] {"message":"An error occurred while saving the entity changes. See the inner exception for details.\nThe INSERT statement conflicted with the FOREIGN KEY constraint \"FK__Tasks__StatusId__6477ECF3\". The conflict occurred in database \"Nikhil_ToDoApp\", table \"dbo.Statuses\", column 'StatusId'.\n","user":"1","endPoint":"ToDoAppWebApi.Controllers.TasksController.AddTask (ToDoAppWebApi)"}
